Repository rachellhill/A-Plus-Films, pull requests merged in 2022-05, with the labels that each got.

#3 Setup/app
  src/App.css
  src/App.js
  src/components/App.js
  src/components/Card.js
  src/components/Movies.js
  src/components/Nav.js
  src/images/hbo.png
  src/index.css
  src/index.js
  src/logo.svg
  src/mockData.js
  src/styles/App.css
  src/styles/Card.css
  src/styles/Movies.css
  src/styles/Nav.css
  src/testing/App.test.js
Labels: enhancement, MVP

#4 Fix a bug where movie posters werent displaying correctly
  src/components/Movies.js
  src/styles/App.css
  src/styles/Card.css
Labels: bug, low priority

#16 Add functionality for home button
  src/components/App.js
  src/components/Card.js
  src/components/Movies.js
  src/components/Nav.js
  src/styles/Nav.css
Labels: enhancement, MVP, high priority

#18 Add error handling to api calls
  src/components/App.js
  src/components/Error.js
  src/components/Movie.js
  src/components/Trailers.js
  src/images/dino-dinosaur.png
  src/styles/Error.css
Labels: enhancement, MVP, high priority
